// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from '@supabase/ssr';
import type { Database } from './types';

// SSO da Young (02/10/2026): sessão em COOKIE no domínio pai .youngempreendimentos.com.br
// (@supabase/ssr), e não no localStorage — logar em qualquer sistema vale em todos.
// Em localhost o cookie fica só no host local. Regra: signOut SEMPRE com { scope: 'local' }.
const YOUNG_DOMAIN = 'youngempreendimentos.com.br'
const _host = typeof window !== 'undefined' ? window.location.hostname : ''
const SSO_COOKIE_OPTIONS = {
  domain: _host === YOUNG_DOMAIN || _host.endsWith('.' + YOUNG_DOMAIN) ? '.' + YOUNG_DOMAIN : undefined,
  path: '/',
  sameSite: 'lax' as const,
  secure: typeof window !== 'undefined' ? window.location.protocol === 'https:' : true,
}

const SUPABASE_URL = "https://vvtympzatclvjaqucebr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dHltcHphdGNsdmphcXVjZWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NTI1NzYsImV4cCI6MjA4NjAyODU3Nn0.C8vWcljx6veAQ0hCi0ms7Ixm6NxhSdWBDeRgUy2Kz50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createBrowserClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  cookieOptions: SSO_COOKIE_OPTIONS,
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Client para o schema dedicado "perdigueiro" (mesma conexao/auth do supabase acima).
// O cast "as unknown as public" e so de tipagem: os tipos gerados so conhecem o schema
// public; em runtime o cliente vai para o schema perdigueiro. (Mesmo padrao do RH/Pilares.)
export const perdigueiroDb = (supabase as any).schema("perdigueiro") as any;